# Generated by Django 5.1.1 on 2024-11-02 05:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_status', models.CharField(blank=True, choices=[('TASKS', 'Tasks'), ('DONE', 'Done'), ('IN_MAKING', 'In Making')], default='Tasks', max_length=50)),
                ('is_private', models.BooleanField(default=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('list_of_item_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
