# Generated by Django 5.1.1 on 2024-11-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='script_count',
            field=models.IntegerField(default=0),
        ),
    ]
