# Generated by Django 5.1.1 on 2024-11-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_friends_user_friends_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='task_count',
            field=models.IntegerField(default=0),
        ),
    ]
