# Generated by Django 5.0.6 on 2024-10-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='List_of_sources',
            field=models.JSONField(default=list),
        ),
    ]
