# Generated by Django 5.0.6 on 2024-10-10 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0002_script_list_of_sources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='List_of_sources',
            new_name='list_of_sources_urls',
        ),
    ]
