# Generated by Django 5.0.6 on 2024-10-10 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0005_script_list_of_shot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='list_of_shot',
            new_name='list_of_shots',
        ),
    ]
