# Generated by Django 5.0.6 on 2024-10-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0006_rename_list_of_shot_script_list_of_shots'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='list_of_Paragraphs',
            field=models.JSONField(default=list),
        ),
    ]
