# Generated by Django 5.0.6 on 2024-10-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0007_script_list_of_paragraphs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='list_of_Paragraphs',
            new_name='list_of_paragraphs',
        ),
        migrations.AddField(
            model_name='script',
            name='list_of_examples',
            field=models.JSONField(default=list),
        ),
    ]
