# Generated by Django 5.0.6 on 2024-10-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0008_rename_list_of_paragraphs_script_list_of_paragraphs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='list_of_colors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='script',
            name='list_of_icons',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='script',
            name='list_of_images',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='script',
            name='list_of_musics',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='script',
            name='list_of_sound_effects',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='script',
            name='list_of_videos_background',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='script',
            name='list_of_visual_effects',
            field=models.JSONField(default=list),
        ),
    ]
