# Generated by Django 5.0.6 on 2024-10-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0009_script_list_of_colors_script_list_of_icons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
