# Generated by Django 5.1.1 on 2024-10-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0010_script_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='list_of_colors',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='list_of_examples',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='list_of_fonts_urls',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='list_of_icons',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='list_of_images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='list_of_musics',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='list_of_paragraphs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='list_of_shots',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='list_of_sound_effects',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='list_of_sources_urls',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='list_of_videos_background',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='list_of_visual_effects',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
