# Generated by Django 5.1.1 on 2024-10-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0011_alter_script_list_of_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='list_of_transitions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
