# Generated by Django 5.1.1 on 2024-11-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0012_script_list_of_transitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
