# Generated by Django 5.1.1 on 2024-11-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0013_script_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='script_status',
            field=models.CharField(choices=[('TASKS', 'Tasks'), ('DONE', 'Dane'), ('IN_MAKING', 'In Making')], default='Tasks', max_length=50),
        ),
    ]
