# Generated by Django 5.1.1 on 2024-11-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0014_script_script_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='script_status',
            field=models.CharField(choices=[('TASKS', 'Tasks'), ('DONE', 'Done'), ('IN_MAKING', 'In Making')], default='Tasks', max_length=50),
        ),
    ]
